[build]
  command = "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && rustup default stable && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  RUST_LOG = "error"
